### ISSUE TITLE
Outdated source code

### ISSUE THREAD

**Issue by henninglive** [ucarion/rust-lcs#1]
The version of this crate published here on GitHub looks like it's outdated compared to version on crates.io. Could you please publish the version that's available on crates.io.

**Comment by ucarion** [comment]
I wrote this crate on another computer, I'm not sure I'll be able to do this, sorry! I'll definitely try, though.

An older version (v0.1.1) is available both on Github and crates.io, however. I don't remember if there is a difference between 0.1.1 and 0.2.0.

**Comment by henninglive** [comment]
The documentation available on [ulysse.io/rust-lcs/](http://ulysse.io/rust-lcs/) and in the `gh-pages` branch looks like is for the 0.2.0. version. it's definitely not for the 0.1.1 version because the api is slightly different. In the documentation subsequences are returned as `Vec<(&T, &T)>`, while 0.1.1 returns them as `Vec<&T>`.
